image: ubuntu:latest

before_script:
    # Download arduino-cli & library dependencies
    - chmod +x setup-install.sh # Change permission to execute setup-install.sh
    - ./setup-install.sh # Execute setup-install.sh

# Define stages of the pipeline
stages: 
    - build
    - deploy


# Build for Environment & Game terminals
build-arduino:
    
    stage: build

    tags:
        - docker

    script:
        - chmod +x ci-build-arduino.sh # Change permission to execute ci-build-arduino.sh
        - ./ci-build-arduino.sh # Execute ci-build-arduino.sh


# Build for web app
build-web-app:

    stage: build

    tags:
        - docker

    script:
        # Change directory to src folder of web app
        - cd Web/pll-web-app/src

        # Add mqtt credentials
        - echo "export const HOST = '$WEB_MQTT_HOST';" > credentials.js

        # Move back to web app directory before build
        - cd ..

        # Build web app
        - npm run build

    artifacts:

        # Save build directory artifact for web app deploy job
        paths: 
            - Web/pll-web-app/dist


# Deployment for web app
deploy-web-app:

    stage: deploy

    tags:
        - docker

    script: 

        - echo "Deploying Project.."
        
        # Deploy build artifact to website production
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir Web/pll-web-app/dist --prod 

    only:
        # Only deploy when the main branch is updated
        - main